In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
# create a simple feedforward neural net with 1 hidden layer
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 2)
        self.fc2 = nn.Linear(2, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [3]:
# instantiate two models
model1 = Net()
model2 = Net()

In [6]:
dict(model1.named_parameters())

{'fc1.weight': Parameter containing:
 tensor([[ 0.4587,  0.2876],
         [ 0.3102, -0.0838]], requires_grad=True),
 'fc1.bias': Parameter containing:
 tensor([-0.6388,  0.6372], requires_grad=True),
 'fc2.weight': Parameter containing:
 tensor([[0.1490, 0.6845]], requires_grad=True),
 'fc2.bias': Parameter containing:
 tensor([0.0091], requires_grad=True)}

In [31]:
# instantiate the combined model
combined_model = Net()

In [32]:
alpha = nn.Parameter(torch.randn(1))
beta = nn.Parameter(torch.randn(1))

In [34]:
param_names = [name for name, _ in combined_model.named_parameters()]

for name in param_names:
    print(f'replacing {name}')
    # del eval(f'combined_model.{name}')
    exec(f'del combined_model.{name}')
    # x = alpha * eval(f'model1.{name}') + beta * eval(f'model2.{name}')
    exec(f'combined_model.{name} = alpha * model1.{name} + beta * model2.{name}')

fc1.bias : Parameter containing:
tensor([0.3785, 0.6520], requires_grad=True)
fc2.weight : Parameter containing:
tensor([[-0.0089, -0.6642]], requires_grad=True)
fc2.bias : Parameter containing:
tensor([-0.4093], requires_grad=True)


In [35]:
dict(combined_model.named_parameters())

{}

In [ ]:
x = torch.tensor([1., 1.])
y = combined_model(x)
y.backward()

print(f'alpha.grad = {alpha.grad}')
print(f'beta.grad = {beta.grad}')